# Generated by Django 5.1.1 on 2024-11-03 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Solo', 'Solo'), ('Versus', 'Versus')], max_length=50)),
                ('public', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Complete', 'Complete')], max_length=50)),
                ('game_length', models.IntegerField()),
                ('player_one_score', models.IntegerField()),
                ('player_two_score', models.IntegerField(blank=True, null=True)),
                ('trajectories', models.JSONField(blank=True, null=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_answer', models.CharField(max_length=255)),
                ('solo_games_played', models.IntegerField(default=0)),
                ('solo_high_score', models.IntegerField(default=0)),
                ('solo_high_time', models.IntegerField(default=0)),
                ('versus_games_played', models.IntegerField(default=0)),
                ('versus_high_score', models.IntegerField(default=0)),
                ('versus_high_time', models.IntegerField(default=0)),
                ('versus_wins', models.IntegerField(default=0)),
                ('versus_losses', models.IntegerField(default=0)),
                ('item_history', models.JSONField()),
                ('settings', models.JSONField()),
                ('user_points', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='api.item')),
                ('security_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.securityquestion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
